name: test
on: 
 - push
 - pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v3
      - name: install dependencies
        run: yarn
      - name: module prepare
        run: yarn dev:prepare
      - name: test
        run: yarn test